version: '3.4'

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=asdfjkl-123

    birdmap.api:
        image: ${DOCKER_REGISTRY-}birdmapapi
        ports:
            - "8000:80"
            - "5001:443"
        build:
          context: .
          dockerfile: Birdmap.API/Dockerfile
        depends_on:
            - db
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
