version: '3.4'

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=RPSsql12345

    birdmap.api:
        image: ${DOCKER_REGISTRY-}birdmapapi
        ports:
            - "8000:80"
            - "8001:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        build:
          context: .
          dockerfile: Birdmap.API/Dockerfile
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_HTTPS_PORT=8001
            - Birdmap_Kestrel__Certificates__Default__Password=certpass123
            - Birdmap_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
            - Birdmap_Secret=7gz;]=bQe}n#3~RwC+Y<SrjoE:sHwO
            - Birdmap_LocalDbConnectionString=Data Source=db;Initial Catalog=birdmap;User=sa;Password=RPSsql12345
            - Birdmap_Defaults__Users__0__Name=admin
            - Birdmap_Defaults__Users__0__Password=pass
            - Birdmap_Defaults__Users__0__Role=Admin
            - Birdmap_Defaults__Users__1__Name=user
            - Birdmap_Defaults__Users__1__Password=pass
            - Birdmap_Defaults__Users__1__Role=User
            - Birdmap_Defaults__Services__Local-Database=https://localhost:8001/health
            - Birdmap_Defaults__Services__KMLabz-Service=https://birb.k8s.kmlabz.com/devices
            - Birdmap_UseDummyServices=true
            - Birdmap_ServicesBaseUrl=https://birb.k8s.kmlabz.com/
            - Birdmap_Mqtt__BrokerHostSettings__Host=localhost
            - Birdmap_Mqtt__BrokerHostSettings__Port=1883
            - Birdmap_Mqtt__ClientSettings__Id=ASP.NET Core client
            - Birdmap_Mqtt__ClientSettings__Username=username
            - Birdmap_Mqtt__ClientSettings__Password=password
            - Birdmap_Mqtt__ClientSettings__Topic=devices/output